name: 'Update README'

description: 'Updates README.md with latest repositories.'

inputs:
  token:
    required: true
    description: "Github token"
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      shell: bash
      run: python -m pip install PyGithub

    - name: Run update script
      shell: bash
      run: python ${{ github.action_path }}/update_readme.py
      env:
        GITHUB_TOKEN: ${{ inputs.INPUT_TOKEN }}

