name: 'Update README'

description: 'Updates README.md with latest repositories.'

inputs:
  github_token:
    description: 'GitHub Token'
    required: true
  username:
    description: 'GitHub Username'
    required: false
  repo:
    description: "Path of repository which contains the readme."
    required: false
  nrecent:
    description: "Number of recent repositories to show"
    required: false
  type:
    description: "Type of repositories to list in readme. Values: all, owner, member"
    required: false
  sort:
    description: "Sorting type to use. Values: created, updated, pushed, full_name"
    required: false
  direction:
    description: "Direction of sort. Values: asc, desc"
    required: false
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      shell: bash
      run: pip install PyGithub

    - name: Run update script
      shell: bash
      run: python ${{ github.action_path }}/update_readme.py
