name: 'Update README'

description: 'Updates README.md with latest repositories.'

inputs:
  token:
    required: true
    description: "Github token"
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: python
      run: python -m pip install PyGithub

    - name: Run update script
      shell: python
      run: update_readme.py
      env:
        GITHUB_TOKEN: ${{ inputs.INPUT_TOKEN }}

