name: 'Update README'

description: 'Updates README.md with latest repositories.'

inputs:
  github_token:
    description: 'GitHub Token'
    required: true
  username:
    description: 'GitHub Username'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'book'
  color: 'blue'
