name: "Update README.md"

inputs:
  github_token:
    description: 'GitHub Token'
    required: false
  username:
    description: 'GitHub Username'
    required: false
  repo:
    description: "Path of repository"
    required: false
  nrecent:
    description: "Number of recent repositories to show"
    required: false
  type:
    description: "Type of repository"
    required: false
  sort:
    description: "Sorting type to use"
    required: false
  direction:
    description: "Direction of sort"
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      shell: bash
      run: pip install PyGithub

    - name: Run update script
      shell: bash
      run: python ${{ github.workspace }}/update_readme.py
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN != '' && env.GITHUB_TOKEN || inputs.github_token }}
        INPUT_GITHUB_TOKEN: ${{ env.GITHUB_TOKEN != '' && env.GITHUB_TOKEN || inputs.github_token }}

branding:
  icon: 'book'
  color: 'white'
