name: Update README

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update reamde
        uses: ./.github/actions/update-readme
        env:
          GITHUB_TOKEN: ${{ secrets.UPDATE_README_GITHUB_TOKEN != '' && secrets.UPDATE_README_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
        with:
          github_token: ${{ secrets.UPDATE_README_GITHUB_TOKEN != '' && secrets.UPDATE_README_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
