name: Update README

on:
  push:
    branches:
      - main
    paths-ignore: "README.md"
  workflow_dispatch:
    paths-ignore: "README.md"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Update reamde
        uses: notweerdmonk/update-readme-action-python/.github/actions/update-readme@main
        env:
          GITHUB_TOKEN: ${{ secrets.UPDATE_README_GITHUB_TOKEN != '' && secrets.UPDATE_README_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
        with:
          github_token: ${{ secrets.UPDATE_README_GITHUB_TOKEN != '' && secrets.UPDATE_README_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
